### ISSUE TITLE
unable to upload big such as 200mb file

### ISSUE THREAD

**Issue by Frozen12** [Itz-fork/Mega.nz-Bot#30]
Bot can upload 30MB or smaller file just fine. When i try to upload big file (example 20pMB) bot replies there was an unknown error

**Comment by Itz-fork** [comment]
![Screenshot_2022-05-08-06-14-22_1366x768](https://user-images.githubusercontent.com/77770753/167296761-62d3f82c-4c4f-46c7-be85-5e889a9c0f12.png)

Tested with 100mb file and it works. (Uploaded url: https://mega.nz/#!t4hWwIYI!EnaIUNsgqT5EwWrrWmFcoLvnC1iUaXMPnfsDj_pcqS8)
