### ISSUE TITLE
Error on upload 

### ISSUE THREAD

**Issue by abaddon-66** [Itz-fork/Mega.nz-Bot#33]
Shows email / pass error even if its correct

**Comment by Itz-fork** [comment]
Can you provide a screenshot if possible? For me, it works fine

![Screenshot_2022-05-27-11-29-10_1366x768](https://user-images.githubusercontent.com/77770753/170639695-7926d737-a6a5-4447-acb2-6b8351b4b4a0.png)

**Comment by Itz-fork** [comment]
Fixed in [commit 278](https://github.com/Itz-fork/Mega.nz-Bot/commit/3ef1d7689c9e1c63cd5ffe435c75c8861aa797ff)
