### ISSUE TITLE
 from pyrogram import idle ImportError: cannot import name 'idle' from 'pyrogram'

### ISSUE THREAD

**Issue by ivan-bryliant** [Itz-fork/Mega.nz-Bot#36]
error:```
 Traceback (most recent call last):
  File "C:\Users\Desktop\Mega.nz-Bot-main\megadl\__main__.py", line 6, in <module>
    from pyrogram import idle
ImportError: cannot import name 'idle' from 'pyrogram' (C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\__init__.py)
```

**Comment by Itz-fork** [comment]
Update pyrogram to the latest version (`2.0.30`) and try again
