### ISSUE TITLE
Isn't working on Heroku

### ISSUE THREAD

**Issue by sminato27** [Itz-fork/Mega.nz-Bot#41]
I've deployed successfully on Heroku but it don't works. 

![image](https://user-images.githubusercontent.com/59450675/192426237-1222de9b-67e3-4e06-b4af-f5364c9687a2.png)
![image](https://user-images.githubusercontent.com/59450675/192426262-9379c26a-9764-4775-a010-1e716644f727.png)

**Comment by Itz-fork** [comment]
Check #31

**Comment by sminato27** [comment]
I've deployed correctly but isn't working.

**Comment by Itz-fork** [comment]
it does now
