### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [Itz-fork/Mega.nz-Bot#43]
Hi, In **Mega.nz-Bot**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
pyrogram
TgCrypto
filetype
filesplit
wget
git+https://github.com/Itz-fork/pyro-mega.py.git
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **pyrogram** can be changed to *>=1.0.0,<=2.0.57*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the pyrogram</summary>
 <pre>pyrogram.idle
pyrogram.filters.command
pyrogram.Client
pyrogram.filters.regex
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>login_to_mega
megadl.data.PROCESS_TEXT.format
float
send_errors
open
json.loads
set
join
client.get_me
pyrogram.types.InlineQueryResultArticle
open.close
pyrogram.types.InlineKeyboardButton
megadl.meganzbot.send_message
query.query.strip.split
megadl.helpers_nexa.account.m.get_quota
query.query.strip.lower.strip
TimeFormatter
pyrogram.filters.command
megadl.helpers_nexa.megatools.MegaTools.upload
self.__genErrorMsg
os.environ.get.split
up_file.forward.reply_text
inline_down_butotns.append
run.stdout.read
callbacks.get_buttons
megadl.meganzbot.send_animation
os.remove
megadl.helpers_nexa.account.m.get_public_url_info
print
megadl.helpers_nexa.mega_help.send_logs
megadl.helpers_nexa.mega_help.check_logs
os.environ.get
str
UnknownError
functools.partial
megadl.meganzbot.send_photo
pyrogram.Client.on_inline_query
len
message.reply_text
pyrogram.types.InputTextMessageContent
split_files
time.time
Messages.get
megadl.helpers_nexa.mega_help.humanbytes
megadl.helpers_nexa.megatools.MegaTools.download
megadl.helpers_nexa.account.m.get_user
megadl.meganzbot.send_document
pyrogram.Client.on_message
query.query.strip
up_file.forward
super.__init__
shutil.rmtree
query.message.reply_text
query.query.strip.lower.split
super
mega.Mega
subprocess.Popen.poll
megadl.helpers_nexa.account.m.get_upload_link
get_vid_duration
data.B_START_TEXT.format
data.PROCESS_TEXT.format
megadl.meganzbot.get_chat
megadl.data.get_msg
os.path.isfile
pyrogram.Client
pyrogram.Client.on_callback_query
megadl.helpers_nexa.account.m.import_public_url
os.path.basename
run.stdout.readline
megadl.data.ERROR_TEXT.format
megadl.data.get_msg.format
self.genConfig
megadl.helpers_nexa.mega_help.send_errors
self.runCmd
self.__is_account
megadl.meganzbot.send_video
megadl.data.get_buttons
meganzbot.start
pyrogram.types.InlineKeyboardMarkup
megadl.meganzbot.get_me
asyncio.get_running_loop
self.makeDir
UnableToCreateDirectory
range
dict
filetype.guess
humanbytes
megadl.helpers_nexa.account.m.download_url
os.walk
run.stdout.read.decode
query.edit_message_text
re.match
os.makedirs
os.path.join
client.download_media
os.path.exists
divmod
re.search
megadl.helpers_nexa.megatools.MegaTools
message.text.split
os.stat
math.floor
int
mega.Mega.login
megadl.meganzbot.send_audio
pyrogram.types.InlineKeyboardButton.get
open.write
filesplit.split.Split
run_shell_cmds
query.answer
message.reply
megadl.helpers_nexa.up_helper.guess_and_send
message.reply_text.edit
message.edit
megauplaod_msg.edit.edit
client.answer_inline_query
query.query.strip.lower
round
query.message.delete
self.__checkErrors
megabot.get_me
answers.append
pyrogram.filters.regex
filesplit.split.Split.bysize
exit
subprocess.Popen
pyrogram.idle
megadl.meganzbot.edit_message_text
UploadFailed
json.dumps
asyncio.get_running_loop.run_in_executor
message.reply_text.delete
megadl.helpers_nexa.account.m.get_storage_space
format
os.path.isdir
func
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by Itz-fork** [comment]
Everything should work as expected now
