### ISSUE TITLE
"Unable to find Mega Email and Password" even if I linked a valid account

### ISSUE THREAD

**Issue by binnichtaktiv** [Itz-fork/Mega.nz-Bot#44]
I put my email and password in the config file but I get this. It cant be wrong because i copied from the cofig file and pasted it into mega.nz and it loggin in without problems. So i think there is something wrong
![2022-11-02 09_43_11-binnichtaktiv_Mega nz-Bot_ Simple Telegram Bot to Download and Upload Files From](https://user-images.githubusercontent.com/96953964/199441868-f582ec13-a454-4a3f-9511-f90bca703cb4.png)

**Comment by Aronfinchi** [comment]
https://t.me/YFXcloudTG/23

**Comment by binnichtaktiv** [comment]
> https://t.me/YFXcloudTG/23

?

**Comment by binnichtaktiv** [comment]
> enter there giveway insert your email you will get a MEGA BUSINESS ACCOUNT

🧢

I don’t need your scam

**Comment by Itz-fork** [comment]
Fixed
