### ISSUE TITLE
Not uploading 

### ISSUE THREAD

**Issue by AliAryanTech** [Itz-fork/Mega.nz-Bot#45]
Error: 
>>> Upload failed due to an unknown error.

Please make sure that you've provided the correct username and password.

You can open a new issue if the problem persists - https://github.com/Itz-fork/Mega.nz-Bot/issues

**Comment by Rohandud** [comment]
same issue

**Comment by AliAryanTech** [comment]
> same issue

Fixed fork this repo - [Here](https://github.com/BlackCatDevel0per/Mega.nz-Bot)
