### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Ijal79** [Itz-fork/Mega.nz-Bot#46]
I was deploying this repo on Railway and its crashed because its always showing this error :

AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

Can you fix this? If you can't, can i fix this? or taught me how to fix that?
Thank you

**Comment by SanujaNS** [comment]
This is probably because you are using python 3.11.x version, try using python version 3.10.x or below.
~~~
Note: Support for generator-based coroutines is deprecated and is removed in Python 3.11.
~~~
[https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines](url)

**Comment by Itz-fork** [comment]
Tested on python 3.12
