### ISSUE TITLE
Not able to use on local machine

### ISSUE THREAD

**Issue by Ayush-Kumar-web** [Itz-fork/Mega.nz-Bot#50]
Hey I am getting this error while trying to use this on my local system.
 I am using linux 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ayushk/Music/Mega.nz-Bot/megadl/__main__.py", line 7, in <module>
    from pyrogram import idle
ModuleNotFoundError: No module named 'pyrogram'

this is coming after I tried executing the megadl

**Comment by Itz-fork** [comment]
install requirements using,
```sh
pip3 install -U -r requirements.txt
```

**Comment by Ayush-Kumar-web** [comment]
> install requirements using,
> 
> ```shell
> pip3 install -U -r requirements.txt
> ```

I am using arch Linux 
Is the procedure same?

**Comment by Itz-fork** [comment]
yes. If it doesn't work use installer script,
```sh
curl -sS https://raw.githubusercontent.com/Itz-fork/Mega.nz-Bot/nightly/installer.sh | bash
```
