### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Prince94163** [Itz-fork/Mega.nz-Bot#51]
![Screenshot_2024-01-21-11-29-11-66_74594bd74a0419242537a8d02ba17993](https://github.com/Itz-fork/Mega.nz-Bot/assets/128693609/7bb613f2-924e-428f-af81-ffe7aa045945)

**Comment by Itz-fork** [comment]
Is this your bot? 

If so try updating to the latest version ([f98401e](https://github.com/Itz-fork/Mega.nz-Bot/commit/f98401e6fac7c8644f303a9679f6c7a1f5bdfb53)).

Also if you're using heroku use [X-Bin-Patch](https://github.com/Itz-fork/X-Bin-Patch#deployment) to deploy
