### ISSUE TITLE
The dollar ($) prefixed field '$inc' in '$inc' is not allowed in the context of an update's replacement document.

### ISSUE THREAD

**Issue by crazydeveloper3** [Itz-fork/Mega.nz-Bot#54]
Whenever I try to enter a mega link and tap on download button after it gets 100% finished it shows this error...

Oops 🫨, Somethig bad happend! 

The dollar ($) prefixed field '$inc' in '$inc' is not allowed in the context of an update's replacement document. Consider using an aggregation pipeline with $replaceWith., full error: {'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$inc' in '$inc' is not allowed in the context of an update's replacement document. Consider using an aggregation pipeline with $replaceWith."}

**Comment by Itz-fork** [comment]
Fixed
