### ISSUE TITLE
Error while downloading 

### ISSUE THREAD

**Issue by IlBudda** [Itz-fork/Mega.nz-Bot#55]
I tried single file and folder but with the same result. When the download finishes from this error

WARNING:root:
##### Mega.nz-Bot Error Handler #####

Version: cypher-1.0
Module: megadl.modules.mega_dl
Error:
'NoneType' object has no attribute 'plus_fl_count'

**Comment by Noob0005** [comment]
> I tried single file and folder but with the same result. When the download finishes from this error
> 
> WARNING:root:
> 
> ##### Mega.nz-Bot Error Handler
> Version: cypher-1.0 Module: megadl.modules.mega_dl Error: 'NoneType' object has no attribute 'plus_fl_count'

Yes i m getting this error too
