### ISSUE TITLE
unable to download/upload

### ISSUE THREAD

**Issue by Gyvari060104** [Itz-fork/Mega.nz-Bot#60]
The dollar ($) prefixed field '$inc' in '$inc' is not allowed in the context of an update's replacement document. Consider using an aggregation pipeline with $replaceWith., full error: {'index': 0, 'code': 52, 'errmsg': "The dollar ($) prefixed field '$inc' in '$inc' is not allowed in the context of an update's replacement document. Consider using an aggregation pipeline with $replaceWith."}

**Comment by Itz-fork** [comment]
Should be fixed by now
